
$('#wenshidu').click(function(event){ 
        $(event.target).parent().siblings().children().next().hide();  
        $('iframe').attr("src","wenshidu.html");
        $('#wenshidu').addClass("active");
        $('#jiedian').removeClass("active");
        $('#shipin').removeClass("active");
        $('#cangku').removeClass("active");
      });
      $('#jiedian').click(function(event) {
        $(event.target).parent().siblings().children().next().hide(); 
        $(event.target).next().toggle(350);
        if($(event.target).parent().attr('id')=="topo"){
          $('iframe').attr("src","jiedian.html");
          $(event.target).css('backgroundColor','#eef');
          $(event.target).parent().siblings().children().css('backgroundColor','#F5F5F5');
        }else if ($(event.target).parent().attr('id')=="route") {
           $('iframe').attr("src","routes.html");
           $(event.target).css('backgroundColor','#eef');
          $(event.target).parent().siblings().children().css('backgroundColor','#F5F5F5');         
        }  
        $('#jiedian').addClass("active");
        $('#wenshidu').removeClass("active");
        $('#shipin').removeClass("active");
        $('#cangku').removeClass("active");
      });
      $('#shipin').click(function(event){
      $(event.target).parent().siblings().children().next().hide();      
        $('iframe').attr("src","shipin.html");
        $('#shipin').addClass("active");
        $('#cangku').removeClass("active");
        $('#wenshidu').removeClass("active");
        $('#jiedian').removeClass("active");
      });
      $('#cangku').click(function(event){ 
      $(event.target).parent().siblings().children().next().hide();     
        $('iframe').attr("src","cangku.html");
        $('#cangku').addClass("active");
        $('#wenshidu').removeClass("active");
        $('#jiedian').removeClass("active");
        $('#shipin').removeClass("active");
      });
      $('#nav_cangku').click(function(event){     
        $('iframe').attr("src","cangku.html");
        $('#cangku').addClass("active");
        $('#wenshidu').removeClass("active");
        $('#jiedian').removeClass("active");
        $('#shipin').removeClass("active");
      });
      $('#nav_wenshidu').click(function(event){     
        $('iframe').attr("src","wenshidu.html");
        $('#wenshidu').addClass("active");
        $('#jiedian').removeClass("active");
        $('#shipin').removeClass("active");
        $('#cangku').removeClass("active");
      });
      $('#nav_jiedian').click(function(event){     
        if($(event.target).parent().attr('id')=="nav_topo"){
          $('iframe').attr("src","jiedian.html");
          $(event.target).css('backgroundColor','#eef');
          $(event.target).parent().siblings().children().css('backgroundColor','#F5F5F5');
        }else if ($(event.target).parent().attr('id')=="nav_route") {
           $('iframe').attr("src","routes.html");
           $(event.target).css('backgroundColor','#eef');
          $(event.target).parent().siblings().children().css('backgroundColor','#F5F5F5');         
        }  
        $('#jiedian').addClass("active");
        $('#wenshidu').removeClass("active");
        $('#shipin').removeClass("active");
        $('#cangku').removeClass("active");
      });
      $('#nav_shipin').click(function(event){     
        $('iframe').attr("src","shipin.html");
        $('#shipin').addClass("active");
        $('#cangku').removeClass("active");
        $('#wenshidu').removeClass("active");
        $('#jiedian').removeClass("active");
      });